// @ts-check
/**
 * Bara laterală Edulab58.
 *
 * Un singur sidebar, autogenerat din `docs/`. edumat58 are unsprezece intrări
 * de nivel întâi (EduPAȘI, Automatisme, Arhivă, Ghidul părintelui…), fiindcă a
 * crescut în timp. Aici sunt trei clase și o pagină „Despre" — atât cât există.
 *
 * Ierarhia, aceeași ca pe edumat58: Clasă > Modul > lecție. Etichetele vin din
 * `_category_.json`, nu din cod.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  fizicaSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
